name: Deploy to EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Instance 1
      run: |
        scp -i your-key.pem index.html ec2-user@<IP_INSTANCE_1>:/var/www/html/index.html

    - name: Deploy to Instance 2
      run: |
        scp -i your-key.pem index.html ec2-user@<IP_INSTANCE_2>:/var/www/html/index.html
